# Generated by Django 5.2.1 on 2025-05-17 17:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Texte de la question")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("F", "Facile"), ("M", "Moyen"), ("D", "Difficile")],
                        max_length=1,
                        verbose_name="Difficulté",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["category", "difficulty"],
            },
        ),
        migrations.CreateModel(
            name="QuestionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Catégorie")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Catégorie de question",
                "verbose_name_plural": "Catégories de questions",
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "En préparation"),
                            ("O", "En cours"),
                            ("C", "Terminé"),
                            ("A", "Analyse en cours"),
                            ("D", "Analyse terminée"),
                        ],
                        default="P",
                        max_length=1,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de complétion"
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Candidat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entretien",
                "verbose_name_plural": "Entretiens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_report",
                    models.FileField(
                        blank=True, null=True, upload_to="interview_reports/"
                    ),
                ),
                ("summary", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interview",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="interviewapp.interview",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analyse d'entretien",
                "verbose_name_plural": "Analyses d'entretiens",
            },
        ),
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="interviewapp.interview",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="interviewapp.question",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="interviewapp.questioncategory",
                verbose_name="Catégorie",
            ),
        ),
        migrations.CreateModel(
            name="VideoResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        upload_to="interview_videos/", verbose_name="Fichier vidéo"
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Durée (secondes)"
                    ),
                ),
                (
                    "analysis_result",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Résultat d'analyse"
                    ),
                ),
                (
                    "analysis_completed",
                    models.BooleanField(default=False, verbose_name="Analyse terminée"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interview_question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_response",
                        to="interviewapp.interviewquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse vidéo",
                "verbose_name_plural": "Réponses vidéos",
                "ordering": ["interview_question__order"],
            },
        ),
    ]
