# Generated by Django 5.2.1 on 2025-06-01 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0009_remove_interviewresult_interview_delete_interview_and_more'),
        ('interviewapp', '0003_question_expected_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='Authentication.candidat', verbose_name='Candidat'),
        ),
    ]
