# Generated by Django 5.2.1 on 2025-06-01 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0009_remove_interviewresult_interview_delete_interview_and_more'),
        ('interviewapp', '0004_alter_interview_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='job_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='Authentication.jobapplication', verbose_name='Candidature associée'),
        ),
    ]
