# Generated by Django 5.2.1 on 2025-06-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testreport',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='weaknesses',
        ),
    ]
