# Generated by Django 5.1.7 on 2025-05-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_benefit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary_max',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_min',
        ),
    ]
