# Generated by Django 5.1.7 on 2025-05-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance'), ('alternance', 'Alternance'), ('volontariat', 'Volontariat')], default='cdi', max_length=15),
        ),
    ]
