# Generated by Django 5.1.7 on 2025-05-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance'), ('alternance', 'Alternance'), ('volontariat', 'Volontariat')], default='cdi', max_length=15),
        ),
    ]
