# Generated by Django 5.1.7 on 2025-05-31 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_jobapplication_similarity_score_alter_job_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewresult',
            name='interview',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.DeleteModel(
            name='InterviewResult',
        ),
    ]
