# Generated by Django 5.2.1 on 2025-06-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0009_remove_interviewresult_interview_delete_interview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('reviewing', "En cours d'examen"), ('interview', 'Entretien'), ('tinterview', 'Entretien technique'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée')], default='pending', max_length=10),
        ),
    ]
